### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by iErics** [prohetamine/temp-mail-fuck#3]
I get this error today: 
```
Error: Evaluation failed: SyntaxError: Unexpected token < in JSON at position 0
    at ExecutionContext._evaluateInternal (/Users/yang/Puppeteer/node_modules/temp-mail-fuck/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/yang/Puppeteer/node_modules/temp-mail-fuck/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Object.createMailbox (/Users/yang/Puppeteer/node_modules/temp-mail-fuck/index.js:112:23)
```

**Comment by prohetamine** [comment]
It is quite possible that the library can no longer work, due to the elimination of the vulnerability, use the paid api...

**Comment by iErics** [comment]
> It is quite possible that the library can no longer work, due to the elimination of the vulnerability, use the paid api...

Sorry, the problem is because the proxyman.  The library still can work. Thank for your work.
